// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  abc: string;
  about: string;
  list: string;
  normal: string;
  title: string;
  welcome: string;
}
export const cssExports: CssExports;
export default cssExports;
