// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  current: string;
  normal: string;
  record: string;
}
export const cssExports: CssExports;
export default cssExports;
