name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: yarn && yarn run build:modern --tiny && yarn run build:modern --app treasure-hunter --tiny && yarn run build:modern --app img2font --tiny && yarn run build:modern --app birthday --tiny && yarn run build:modern --app test-react --tiny
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: dist


